"""02_clean: data/raw_tidy.csv -> data/clean.csv (exclusions, derived columns, outcomes, treatment indicator)

Generated by filedrawer 0.1.0. Run from the study folder: python scripts/02_clean.py
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]

OUTCOMES = json.loads("[{\"name\": \"post_ap\", \"label\": \"Affective polarization after treatment\", \"kind\": \"single_item\", \"columns\": [\"post_ap\"], \"reverse\": [], \"scale\": [-100, 100], \"construction\": \"In-party minus out-party thermometer\"}, {\"name\": \"post_udp\", \"label\": \"Support for undemocratic practices\", \"kind\": \"single_item\", \"columns\": [\"post_udp\"], \"reverse\": [], \"scale\": [1, 7], \"construction\": \"Mean of the four items answered\"}]")
EXCLUSIONS = ["screener_pass == 1", "partisan in ['Democrat','Republican']", "arm != 'T33'"]
DERIVED = json.loads("{}")
ARM_COL = "arm"
TREATED = ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10", "T11", "T12", "T13", "T14", "T15", "T16", "T17", "T18", "T19", "T20", "T21", "T22", "T23", "T24", "T25", "T26", "T27", "T28", "T29", "T30", "T31", "T32"]            # list of treated arm values (strings)
CONTROL = "T0"
ARM_LABELS = json.loads("{\"T0\": \"Control\", \"T1\": \"Cooperation infographic\", \"T2\": \"Bipartisan bills graph\", \"T3\": \"Bipartisan elite quotes\", \"T4\": \"Shared values exercise\", \"T5\": \"Cross-partisan dialogue guide\", \"T6\": \"Meta-dehumanization correction\", \"T7\": \"Perception survey (form)\", \"T8\": \"Common-ground articles\", \"T9\": \"Patriotic article\", \"T10\": \"14th Amendment video\", \"T11\": \"Congressional softball video\", \"T12\": \"iSideWith quiz\", \"T13\": \"Rick and Morty perspective-taking\", \"T14\": \"Bren\\u00e9 Brown empathy video\", \"T15\": \"Perception gap video\", \"T16\": \"'What makes an American' video\", \"T17\": \"McCain defends Obama video\", \"T18\": \"Egyptian revolution video\", \"T19\": \"Cross-partisan friendship TED talk\", \"T20\": \"American history video\", \"T21\": \"Party-tailored videos\", \"T22\": \"Jubilee free speech panel\", \"T23\": \"Jubilee video\", \"T24\": \"Media-profits-from-division image\", \"T25\": \"Shared priorities (Pew) table\", \"T26\": \"Bipartisan legislation examples\", \"T27\": \"Common threat (Russia)\", \"T28\": \"Pro-democracy excerpt\", \"T29\": \"Biden\\u2013DeSantis cooperation\", \"T30\": \"Scandals, both parties (labeled)\", \"T31\": \"Scandals (labels revealed later)\", \"T32\": \"Perception gap quiz\", \"T33\": \"GPT-3 chatbot (excluded)\"}")

def arm_str(v):
    """Canonical arm value: integral numbers (1, 1.0, "1.0") -> "1"."""
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return None
    sv = str(v).strip()
    try:
        f = float(sv)
    except ValueError:
        return sv
    return str(int(f)) if f.is_integer() else sv

def construct(df, o):
    kind = o.get("kind", "mean_items")
    lo, hi = o.get("scale") or [None, None]
    if kind == "single_item":
        return pd.to_numeric(df[o["columns"][0]], errors="coerce")
    if kind == "mean_items":
        parts = []
        for c in o["columns"]:
            s = pd.to_numeric(df[c], errors="coerce")
            if c in (o.get("reverse") or []) and lo is not None:
                s = (lo + hi) - s
            parts.append(s)
        return pd.concat(parts, axis=1).mean(axis=1, skipna=False)
    raise SystemExit(f"outcome {o['name']} has kind={kind}; custom construction must be implemented in this script")

def main():
    df = pd.read_csv(ROOT / "data" / "raw_tidy.csv")
    n0 = len(df)
    for expr in EXCLUSIONS:
        try:
            df = df.query(expr)
        except Exception as e:
            print(f"WARNING: exclusion {expr!r} could not be applied: {e}")
    print(f"sample: {n0} -> {len(df)} after exclusions {EXCLUSIONS}")
    for col, expr in DERIVED.items():
        try:
            df[col] = df.eval(expr)
        except Exception as e:
            raise SystemExit(f"derived column {col!r} = {expr!r} could not be computed: {e}")
        print(f"derived {col} = {expr}: mean={pd.to_numeric(df[col], errors='coerce').mean():.3f}")
    if ARM_COL and ARM_COL in df.columns:
        df["arm_code"] = df[ARM_COL].map(arm_str)
        keep = [a for a in TREATED + [CONTROL] if a is not None]
        df = df[df["arm_code"].isin(keep)].copy()
        df["treat"] = df["arm_code"].isin(TREATED).astype(int)
        df["arm"] = df["arm_code"].map(lambda a: ARM_LABELS.get(a, a))
        print(f"arms: {df['arm_code'].value_counts().sort_index().to_dict()}")
    for o in OUTCOMES:
        df[o["name"]] = construct(df, o)
        print(f"outcome {o['name']}: mean={df[o['name']].mean():.3f} sd={df[o['name']].std():.3f} missing={int(df[o['name']].isna().sum())}")
    (ROOT / "data").mkdir(exist_ok=True)
    df.to_csv(ROOT / "data" / "clean.csv", index=False)
    print(f"wrote data/clean.csv: {len(df)} rows, {df.shape[1]} columns")

if __name__ == "__main__":
    main()
